### ISSUE TITLE
I am working on similar app for Windows :)

### ISSUE THREAD

**Issue by GamerClassN7** [muniter/halinuxcompanion#27]
Hello,
I just wanted to ask if it is OK that i include link to your repo inside my readme file for windows companion app ? 

![image](https://github.com/muniter/halinuxcompanion/assets/22167469/9317f17e-59b7-491e-9ff4-fbc598ac83ae)
https://github.com/GamerClassN7/HA_Desktop_Companion/blob/master/README.md

**Comment by muniter** [comment]
Sure thing! Have fun building your app!! Thanks
