### ISSUE TITLE
[BUG] - ??

### ISSUE THREAD

**Issue by MatzeP** [muniter/halinuxcompanion#29]
Hi,
here my errormessage,

chef@PC:/halinuxcompanion$ python3 -V
Python 3.12.3
chef@PC:/halinuxcompanion$ python3.12 -m halinuxcompanion --config config.json
INFO:halinuxcompanion:Reading configuration file config.json
Traceback (most recent call last):
File "", line 198, in _run_module_as_main
File "", line 88, in _run_code
File "/home/chef/halinuxcompanion/halinuxcompanion/main.py", line 104, in
loop.run_until_complete(main())
File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
return future.result()
^^^^^^^^^^^^^^^
File "/home/chef/halinuxcompanion/halinuxcompanion/main.py", line 64, in main
companion = Companion(config) # Companion objet where configuration is stored
^^^^^^^^^^^^^^^^^
File "/home/chef/halinuxcompanion/halinuxcompanion/companion.py", line 99, in init
parsed = CompanionConfig.model_validate(config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'CompanionConfig' has no attribute 'model_validate'

Can anybody help me?

Thanks

**Comment by slovdahl** [comment]
@MatzeP Did you install all the dependencies?

**Comment by MatzeP** [comment]
Hi,
I hope. I can't use the file and I must install the packages one by one.

**Comment by slovdahl** [comment]
> I can't use the file

Can you be more specific, what file and why can't you use it?

And overall, what are you trying to do? If you are just trying to use this Python application, you should probably install it using `pip` instead, preferrably in a Python virtual environment.

**Comment by MatzeP** [comment]
Hi,

the File "requirements.txt"

**Linux**:~/halinuxcompanion$ pip3 install -r requirements.txt
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

**Than I open the file and have go step by step:**
With pip and pip3 I always have this message: 
! pip is installed !
--> sudo apt install pip
-> python3-pip ist schon die neueste Version (24.0+dfsg-1ubuntu1).

**Example for all other:**
sudo pip install aiohttp:3.9.5 **OR** sudo pip3 install aiohttp:3.9.5
_error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification._

--> sudo apt install python3-aiohttp   
-> python3-aiohttp ist schon die neueste Version (3.9.1-1ubuntu0.1)

--> sudo apt install python3-psutil
-> python3-psutil ist schon die neueste Version (5.9.8-2build2).

--> sudo apt install python3-dbus-next
-> python3-dbus-next ist schon die neueste Version (0.2.3-3).

--> sudo apt install python3-pytest
-> python3-pytest ist schon die neueste Version (7.4.4-1).

--> sudo apt install python3-pytest-asyncio
-> python3-pytest-asyncio ist schon die neueste Version (0.20.3-1.2).

--> sudo apt install python3-pytest-cov
-> python3-pytest-cov ist schon die neueste Version (4.1.0-1).

--> sudo apt install python3-coverage
-> python3-coverage ist schon die neueste Version (7.4.4+dfsg1-0ubuntu2).

--> sudo apt install python3-pydantic
-> python3-pydantic ist schon die neueste Version (1.10.14-1).

--> sudo apt install python3-greenlet
-> python3-greenlet ist schon die neueste Version (3.0.3-0ubuntu5.1).

For tox I have installed qtox. All other I don't find.
--> sudo apt install qtox
-> qtox ist schon die neueste Version (1.17.6-0.1build5).

**Python:**
--> sudo apt install python3
-> python3 ist schon die neueste Version (3.12.3-0ubuntu2).

--> python3 -m halinuxcompanion --config config.json
-> INFO:halinuxcompanion:Reading configuration file config.json
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/Linux/halinuxcompanion/halinuxcompanion/__main__.py", line 104, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/Linux/halinuxcompanion/halinuxcompanion/__main__.py", line 64, in main
    companion = Companion(config)  # Companion objet where configuration is stored
                ^^^^^^^^^^^^^^^^^
  File "/home/Linux/halinuxcompanion/halinuxcompanion/companion.py", line 99, in __init__
    parsed = CompanionConfig.model_validate(config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'CompanionConfig' has no attribute 'model_validate'

**Comment by slovdahl** [comment]
Thanks for the details, I now understand your problem more clearly.

(Side note, but I wrongly assumed that this Python project has been published to pypi.org. It has not. So at least part of https://github.com/muniter/halinuxcompanion/issues/29#issuecomment-2409994622 is moot.)

I think we should update the [README](https://github.com/muniter/halinuxcompanion?tab=readme-ov-file#instructions). instructions a bit to include the setup of a Python virtual environment as well. Something like this:

```
cd halinuxcompanion
python3 -m venv .venv
source .venv/bin/activate
pip install -r requirements.txt
```

Now, whenever you want to run `halinuxcompanion`, you need to do it through `.venv/bin/python -m halinuxcompanion`, or alternatively run `source .venv/bin/activate` first which puts the virtual environment `python` first on your `PATH`.

WDYT @muniter, should we update them in line with this? I can provide a PR if you agree.

**Comment by MatzeP** [comment]
Thank you. Now it works
