### ISSUE TITLE
[BUG] TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by mk-maddin** [muniter/halinuxcompanion#3]
**Describe the bug**
When I try to start the halinuxcompanion application I receive the error message:
```
root@c294057215b1f:/opt/ha_client# /usr/bin/python3 -m halinuxcompanion -c config.json
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/ha_client/halinuxcompanion/__main__.py", line 2, in <module>
    from halinuxcompanion.dbus import Dbus
  File "/opt/ha_client/halinuxcompanion/dbus.py", line 54, in <module>
    class Dbus:
  File "/opt/ha_client/halinuxcompanion/dbus.py", line 57, in Dbus
    interfaces: dict[str, ProxyInterface] = {}
TypeError: 'type' object is not subscriptable
```
I am running the app on Debian 10 - 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux

**To Reproduce**
1. install app as described within: https://github.com/muniter/halinuxcompanion#how-to
2. cd into installation directory
3. /usr/bin/python3 -m halinuxcompanion -c config.json

**Expected behavior**
halinuxcompanion app is started.

**Application Logs**
Find verbose log of command: _/usr/bin/python3 -v -m halinuxcompanion -c config.json_ attached.
[verbose.log](https://github.com/muniter/halinuxcompanion/files/7797646/verbose.log)

**Comment by muniter** [comment]
Hello, can you test with a newer python version, like 3.10 perhaps?

**Comment by mk-maddin** [comment]
Unfortunately I cannot see that a newer python3 version is available in official Debian10 repos, and to be truth I do not want to include additional repos into sources within my productive machine as I do not have any idea on the affects to other components.

What I never the less can do is setup a test machine but this will take some short time and I will have to verify first the issue exists there, too.

**Comment by mk-maddin** [comment]
I have setup a test machine with same debian build etc. and found the same error there.
As requested I have installed Python 3.10 then (following this guide: https://unixcop.com/how-to-install-python-3-10-on-debian-11/ - there is no .deb package for Python 3.10 available as I see it at the moment).
Reinstalled pip requirements via:
`pip3.10 install -r requirements.txt`

and executed halinuxcompanion again with following result:
`root@c294057215b1f:/opt/ha_client# python3.10 -m halinuxcompanion -c config.json
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/ha_client/halinuxcompanion/__main__.py", line 8, in <module>
    from halinuxcompanion.sensors.uptime import Uptime
  File "/opt/ha_client/halinuxcompanion/sensors/uptime.py", line 3, in <module>
    import pytz
ModuleNotFoundError: No module named 'pytz'`

So i manually installed: 
`pip3.10 install pytz`

and it seems to work afterwards :)

So now we know that there seems to be a dependency to Python 3.10 (and incompatibility with Python <= 3.7 - 3.8 & 3.9 still unclear)
How is this continued?

**Comment by muniter** [comment]
Thanks for testing. About pytz is a dependency I was testing recently, i believe I can remove it. Will take a look if I can make the application compatible with 3.9 which seems to ship with most distros.
